### ISSUE TITLE
Tests are failing

### ISSUE THREAD

**Issue by waipeng** [stackalytics/default_data#286]
Tests are failing for all new PR with the following error

```
=========================
Failures during discovery
=========================
--- import errors ---
Failed to import test module: tests.test_config_files
Traceback (most recent call last):
  File "/opt/python/3.6.7/lib/python3.6/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/opt/python/3.6.7/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/home/travis/build/stackalytics/default_data/tests/test_config_files.py", line 20, in <module>
    import six
ModuleNotFoundError: No module named 'six'
```

This is the use of six for py2/3 compatibility, which is no longer needed now running py36 tox.

I have sent up a PR #284 that should fix this.

**Comment by waipeng** [comment]
Hm I am confused if this should be the correct please to send PR, as I've just found https://review.opendev.org/q/project:x/stackalytics

Anyone can help?
